from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ContextManager, Mapping, Protocol, runtime_checkable


@dataclass(frozen=True, slots=True)
class TransferStatus:
    kind: str
    provider_status: str
    post_ids: tuple[str, ...] = ()
    error: str | None = None
    final_phase: str | None = None


@runtime_checkable
class PublicationAuthority(Protocol):
    def lock(self, key: str) -> ContextManager[None]: ...
    def list(self, project_id: str | None = None) -> list[dict[str, Any]]: ...
    def get(self, identifier: str) -> dict[str, Any]: ...
    def request(self, request_id: str) -> dict[str, Any] | None: ...
    def reserve(self, record: dict[str, Any], media: bytes) -> dict[str, Any]: ...
    def update(self, identifier: str, **patch: Any) -> dict[str, Any]: ...
    def attempt(self, identifier: str, stage: str, status: str) -> None: ...
    def attempts(self, identifier: str) -> list[dict[str, Any]]: ...
    def delivery(self, token_sha: str) -> tuple[dict[str, Any], bytes]: ...


@runtime_checkable
class SocialPublisherAdapter(Protocol):
    provider: str

    def capabilities(self) -> Mapping[str, Any]: ...
    def connection(self, *, verify: bool = True) -> dict[str, Any]: ...
    def normalize_review(self, request: Mapping[str, Any]) -> dict[str, Any]: ...
    def request_fingerprint(self, project_id: str, review: Mapping[str, Any]) -> str: ...
    def validate_review(self, review: Mapping[str, Any], connection: Mapping[str, Any]) -> None: ...
    def build_delivery(self, png: bytes, digest: str) -> bytes: ...
    def account(self, connection: Mapping[str, Any]) -> dict[str, Any]: ...
    def account_matches(self, specification: Mapping[str, Any]) -> bool: ...
    def provider_specification(
        self, review: Mapping[str, Any], artifact: Mapping[str, Any],
        connection: Mapping[str, Any], delivery: bytes,
    ) -> dict[str, Any]: ...
    def state(self, record: Mapping[str, Any]) -> dict[str, Any]: ...
    def state_patch(self, **canonical: Any) -> dict[str, Any]: ...
    def compatibility(self, record: Mapping[str, Any], state: Mapping[str, Any]) -> dict[str, Any]: ...
    def create_transfer(self, media_url: str, specification: Mapping[str, Any]) -> str: ...
    def transfer_status(self, identifier: str, specification: Mapping[str, Any]) -> TransferStatus: ...
    def commit(self, identifier: str, specification: Mapping[str, Any]) -> tuple[str, ...]: ...
    def resolve(self, post_ids: tuple[str, ...], specification: Mapping[str, Any]) -> dict[str, Any]: ...
    def classify_error(self, error: Exception, *, uncertain: bool) -> str: ...
    def public_error(self, error: Exception, *, uncertain: bool) -> str: ...
    def wait(self, seconds: float) -> None: ...
