import 'package:ptw/features/share/share_models.dart';
import 'package:ptw/models/ptw_image_ref.dart';

ShareCardData sampleShareCard(
  ShareTemplateType template, {
  int variationIndex = 0,
}) => ShareCardData(
  projectId: 'challenge_red_friday',
  template: template,
  event: ShareEvent.manual,
  ownerName: 'Alex',
  ownerHandle: 'alexbuilds',
  ownerAvatarAsset: 'assets/images/users/alex.jpg',
  background: const PtwImageRef.asset('assets/images/backgrounds/startup.jpg'),
  challengeTitle: 'Launch Red Friday and reach 100 active users',
  deadline: DateTime(2026, 10, 1),
  primaryColor: 0xFFF4066E,
  hook: switch (template) {
    ShareTemplateType.challenge => 'Tell me why I won’t.',
    ShareTemplateType.criticism => 'Let’s see.',
    ShareTemplateType.progress => 'They said nobody would join.',
    ShareTemplateType.milestone => 'Proof beats promises.',
    ShareTemplateType.result => 'The deadline arrived. So did I.',
    ShareTemplateType.opinionChange => 'The best kind of update.',
  },
  caption: 'I made the goal public. What do you think happens next?',
  cta: 'See the full journey',
  gradientVariant: variationIndex,
  supporterCount: 148,
  skepticCount: 36,
  commentCount: 184,
  dayNumber: 18,
  progressValue: '127',
  progressMetric: 'people following',
  progressSecondary: '38 honest reactions',
  featuredComment: 'Nobody needs another social app.',
  authorResponse: 'Let’s see.',
  milestone: 'First 100 users',
  resultLead: '90 days ago',
  resultOutcome: 'Goal completed.',
  doubtPercent: 74,
  opinionChange: 'My biggest critic changed their mind.',
  usesFallbackData: false,
  variationIndex: variationIndex,
);
