import { ExternalLink, LoaderCircle, RefreshCcw, ShieldCheck, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { ApiClient } from '../api'
import { translate, type Language } from '../i18n'
type Status = { status: 'authorized'|'authorization_required'|'authorizing'|'verifying'|'failed'; test_status: 'passed'|'failed'|null; authorization_url?: string; device_code?: string }
export function AuthorizationSettings({ api, language, onClose }: { api: ApiClient; language: Language; onClose: () => void }) {
  const [value, setValue] = useState<Status | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const tr = (en: string, uk: string) => translate(language, en, uk)
  const load = async () => { try { setValue(await api.get<Status>('/api/v1/settings/chatgpt-authorization')); setError('') } catch (cause) { setError((cause as Error).message) } }
  useEffect(() => { void load() }, [api])
  useEffect(() => { if (!value || !['authorizing', 'verifying'].includes(value.status)) return; const id = window.setInterval(() => void load(), 2000); return () => window.clearInterval(id) }, [value?.status])
  const refresh = async () => { setBusy(true); try { setValue(await api.post<Status>('/api/v1/settings/chatgpt-authorization/refresh', {})) } catch (cause) { setError((cause as Error).message) } finally { setBusy(false) } }
  const status = value?.status || 'loading'; const label = status === 'authorized' ? tr(value?.test_status === 'passed' ? 'Authorized and verified' : 'Authorized', value?.test_status === 'passed' ? 'Авторизовано й перевірено' : 'Авторизовано') : status === 'authorizing' ? tr('Waiting for authorization', 'Очікується авторизація') : status === 'verifying' ? tr('Verifying ChatGPT/Codex CLI', 'Перевіряється ChatGPT/Codex CLI') : status === 'failed' ? tr('Authorization check failed', 'Перевірка авторизації не вдалася') : tr('Authorization required', 'Потрібна авторизація')
  return <div className="modal-backdrop"><section className="panel settings-dialog" role="dialog" aria-modal="true" aria-labelledby="chatgpt-authorization-title"><header><div><small>{tr('SETTINGS', 'НАЛАШТУВАННЯ')}</small><h2 id="chatgpt-authorization-title">ChatGPT Authorization</h2></div><button className="icon-button" onClick={onClose} aria-label={tr('Close settings', 'Закрити налаштування')}><X /></button></header><div className="authorization-status" role="status"><ShieldCheck /><div><small>{tr('CURRENT STATUS', 'ПОТОЧНИЙ СТАН')}</small><strong>{label}</strong>{value?.test_status === 'passed' && <span>{tr('Working test request passed.', 'Робочий тестовий запит пройдено.')}</span>}</div></div>{value?.status === 'authorizing' && <div className="authorization-device"><p>{tr('Open the secure device page and enter the code. This window updates automatically.', 'Відкрийте захищену сторінку пристрою та введіть код. Це вікно оновиться автоматично.')}</p>{value.authorization_url && <a className="secondary" href={value.authorization_url} target="_blank" rel="noreferrer"><ExternalLink />{tr('Open authorization page', 'Відкрити сторінку авторизації')}</a>}{value.device_code ? <code>{value.device_code}</code> : <p><LoaderCircle className="spin" /> {tr('Preparing secure device prompt…', 'Готується захищене запрошення…')}</p>}</div>}{error && <p role="alert">{error}</p>}<footer><button className="primary" disabled={busy || ['authorizing','verifying'].includes(status)} onClick={() => void refresh()}>{busy ? <LoaderCircle className="spin" /> : <RefreshCcw />}{tr('Refresh authorization', 'Оновити авторизацію')}</button></footer></section></div>
}
