import natalContacts from '../../../../validation_pipeline/studio_assets/natal-contacts.json'
import type { ReactNode } from 'react'
import type { LandingConfiguration, LandingContent, LandingMarketingConfiguration } from '../types'
import type { Section } from './model'
import { EditableColorField } from '../components/EditableColorField'
import { gradients, initialMarketingContent, marketingDefaults, marketingContentDefaults } from './marketing'

type Props = { recommended?: LandingMarketingConfiguration; section: Section; configuration: LandingConfiguration; content: LandingContent; language: 'uk' | 'en'; onConfiguration: (c: LandingConfiguration) => void; onContent: (c: LandingContent) => void; visual: ReactNode }
export function MarketingInspector({ recommended, section, configuration: c, content: v, language, onConfiguration, onContent, visual }: Props) {
  const uk = language === 'uk', tr = (en: string, ua: string) => uk ? ua : en
  const m = c.marketing, copy = v.marketing || marketingContentDefaults
  const configure = (patch: Partial<LandingMarketingConfiguration>) => onConfiguration({ ...c, marketing: { ...(m || recommended || marketingDefaults), ...patch } })
  const enable = () => { configure({}); onContent({ ...v, contacts: { ...v.contacts, email: v.contacts.email || natalContacts.email, phone: v.contacts.phone || natalContacts.phone }, marketing: initialMarketingContent(v, c.presentation?.language !== 'en') }) }
  const toggle = (key: keyof LandingMarketingConfiguration, label: string) => <label className="landing-field"><span><input type="checkbox" checked={Boolean(m?.[key])} onChange={e => configure({ [key]: e.target.checked })} /> {label}</span></label>
  const text = (label: string, value: string, max: number, update: (value: string) => void) => <label className="landing-field"><span>{label}</span><textarea aria-label={label} value={value} maxLength={max} onChange={e => update(e.target.value)} /></label>
  const field = (key: keyof typeof copy, label: string, max = 300) => text(label, copy[key] as string, max, value => onContent({ ...v, marketing: { ...copy, [key]: value } }))
  if (!m) return section === 'theme' || ['comparison', 'walkthrough', 'values', 'cta', 'downloads'].includes(section) ? <div className="landing-repeater"><p>{tr('Add the gradient, comparison, walkthrough and store sections to this page.', 'Додайте градієнт, порівняння, огляд і кнопки магазинів на цю сторінку.')}</p><button className="secondary" onClick={enable}>{tr('Enable showcase sections', 'Увімкнути секції Showcase')}</button></div> : null
  return <>
    {section === 'theme' && <><h3>{tr('Primary gradient', 'Основний градієнт')}</h3><div className="landing-theme-presets">{gradients.map(g => <button className="landing-theme-preset" key={g.id} aria-pressed={m.gradient_id === g.id} onClick={() => configure({ gradient_id: g.id })}><span style={{ display: 'block', height: 48, borderRadius: 10, background: `linear-gradient(110deg,${g.start},${g.end})` }} /><strong>{g[language]}</strong></button>)}</div><EditableColorField className="landing-field" label={tr('Logo & name color', 'Колір логотипа й назви')} value={m.logo_color} onChange={logo_color => configure({ logo_color })} />{toggle('motifs_enabled', tr('Small Natal logos', 'Маленькі логотипи Natal'))}<label className="landing-field"><span>{tr('Logo motif opacity', 'Прозорість логотипів')}</span><input type="range" aria-label="Logo motif opacity" min="0.03" max="0.25" step="0.01" value={m.motif_opacity} onChange={e => configure({ motif_opacity: Number(e.target.value) })} /></label></>}
    {section === 'features' && <>{toggle('carousel_enabled', tr('Show card carousel', 'Показувати карусель карток'))}{field('introduction', tr('Section introduction', 'Вступ секції'), 360)}{toggle('carousel_autoplay', tr('Animate carousel', 'Анімація каруселі'))}<label className="landing-field"><span>{tr('Seconds per card', 'Секунд на картку')}</span><input aria-label={tr('Seconds per card', 'Секунд на картку')} type="range" min="3" max="12" step="1" value={m.carousel_speed} onChange={e => configure({ carousel_speed: Number(e.target.value) })} /></label></>}
    {section === 'comparison' && <>{toggle('comparison_enabled', tr('Show comparison', 'Показувати порівняння'))}{field('comparison_heading', tr('Comparison heading', 'Заголовок порівняння'), 140)}{copy.comparison_rows.map((row, i) => <div className="landing-repeater" key={i}><label><input type="checkbox" checked={row.enabled} onChange={e => onContent({ ...v, marketing: { ...copy, comparison_rows: copy.comparison_rows.map((r, j) => i === j ? { ...r, enabled: e.target.checked } : r) } })} />{tr('Show row', 'Показувати рядок')} {i + 1}</label>{text(`${tr('Comparison item', 'Пункт порівняння')} ${i + 1}`, row.text, 220, value => onContent({ ...v, marketing: { ...copy, comparison_rows: copy.comparison_rows.map((r, j) => i === j ? { ...r, text: value } : r) } }))}{!row.text && <p className="landing-field-hint">{tr('Provide this item manually in Landing Studio, or hide it.', 'Заповніть цей пункт вручну в Landing Studio або приховайте його.')}</p>}</div>)}</>}
    {section === 'walkthrough' && <>{toggle('walkthrough_enabled', tr('Show how it works', 'Показувати як це працює'))}{field('walkthrough_heading', tr('Walkthrough heading', 'Заголовок огляду'), 140)}{copy.walkthrough_steps.map((row, i) => <div className="landing-repeater" key={i}><label><input type="checkbox" checked={row.enabled} onChange={e => onContent({ ...v, marketing: { ...copy, walkthrough_steps: copy.walkthrough_steps.map((r, j) => i === j ? { ...r, enabled: e.target.checked } : r) } })} />{tr('Show step', 'Показувати крок')} {i + 1}</label>{(['title', 'description'] as const).map(key => text(`${tr('Step', 'Крок')} ${i + 1} · ${key}`, row[key], key === 'title' ? 120 : 300, value => onContent({ ...v, marketing: { ...copy, walkthrough_steps: copy.walkthrough_steps.map((r, j) => i === j ? { ...r, [key]: value } : r) } })))}</div>)}<p className="landing-field-hint">{tr('Generate a complete mockup composition. The agent must include phones in this image; individual screen images contain interiors only.', 'Створіть повну композицію мокапів. Агент має включити телефони в це зображення; окремі екрани містять лише інтерфейс.')}</p>{visual}</>}
    {section === 'visual_break' && <>{toggle('benefits_enabled', tr('Show photo & benefits section', 'Показувати фото й переваги'))}{field('benefits_heading', tr('Benefits heading', 'Заголовок переваг'), 140)}{field('benefits_supporting', tr('Benefits introduction', 'Вступ переваг'))}{field('benefit_highlight_title', tr('Highlight title', 'Заголовок акценту'), 90)}{field('benefit_highlight_text', tr('Highlight description', 'Опис акценту'), 200)}</>}
    {section === 'social_proof' && <>{toggle('reference_reviews_enabled', tr('Show sample review layouts', 'Показувати приклади оформлення відгуків'))}<p className="landing-field-hint">{tr('Sample layouts are not Natal customer evidence. Add your own verified evidence below.', 'Приклади оформлення не є відгуками клієнтів Natal. Додайте власні підтверджені відгуки нижче.')}</p></>}
    {section === 'values' && <>{toggle('benefits_enabled', tr('Show service benefits', 'Показувати переваги сервісу'))}{copy.values.map((row, i) => <div className="landing-repeater" key={i}><label><input type="checkbox" checked={row.enabled} onChange={e => onContent({ ...v, marketing: { ...copy, values: copy.values.map((r, j) => i === j ? { ...r, enabled: e.target.checked } : r) } })} />{tr('Show benefit', 'Показувати перевагу')} {i + 1}</label>{(['title', 'description'] as const).map(key => text(`${tr('Benefit', 'Перевага')} ${i + 1} · ${key}`, row[key], key === 'title' ? 90 : 220, value => onContent({ ...v, marketing: { ...copy, values: copy.values.map((r, j) => i === j ? { ...r, [key]: value } : r) } })))}</div>)}</>}
    {section === 'cta' && <>{toggle('cta_enabled', tr('Show CTA panel', 'Показувати панель CTA'))}{field('cta_heading', tr('CTA heading', 'Заголовок CTA'), 180)}{field('cta_text', tr('CTA supporting text', 'Опис CTA'))}</>}
    {section === 'downloads' && <>{toggle('downloads_enabled', tr('Show store buttons', 'Показувати кнопки магазинів'))}{field('store_label', tr('Store button label', 'Текст кнопок магазинів'), 60)}{field('apple_url', 'App Store URL', 2048)}{field('google_url', 'Google Play URL', 2048)}<label className="landing-field"><span>{tr('Without a store URL', 'Без адреси магазину')}</span><select value={m.missing_store_target} onChange={e => configure({ missing_store_target: e.target.value as 'contacts' | 'hide' })}><option value="contacts">{tr('Go to contacts', 'Перейти до контактів')}</option><option value="hide">{tr('Hide button', 'Приховати кнопку')}</option></select></label>{toggle('footer_enabled', tr('Use showcase footer', 'Використовувати футер Showcase'))}{field('privacy_url', tr('Privacy policy URL', 'Адреса політики конфіденційності'), 2048)}{field('terms_url', tr('Terms URL', 'Адреса публічної оферти'), 2048)}<p className="landing-field-hint">{tr('Both policy labels remain visible in the footer. Each becomes a link after you add its URL.', 'Обидві назви документів залишаються у футері. Кожна стане посиланням після додавання адреси.')}</p></>}
  </>
}
